export const SCREEN_FIRST = 'screen.First'
export const SCREEN_NEW_USER = 'screen.NewUser'
export const SCREEN_EXISTING_USER = 'screen.ExistingUser'
export const SCREEN_HISTORY = 'screen.History'
export const SCREEN_SCAN = 'screen.Scan'
export const SCREEN_CONFIRMATION = 'screen.Confirmation'
